# Generated by Django 5.1.5 on 2025-01-22 22:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المشروع")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رمز المشروع"
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف المشروع")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="موقع المشروع"),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء المتوقع")),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء الفعلي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "تخطيط"),
                            ("in_progress", "قيد التنفيذ"),
                            ("on_hold", "متوقف"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="حالة المشروع",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="الميزانية",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="التكلفة الفعلية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مدير المشروع",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشروع",
                "verbose_name_plural": "المشاريع",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المستند"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "عقد"),
                            ("plan", "مخطط"),
                            ("permit", "تصريح"),
                            ("report", "تقرير"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع المستند",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="project_documents/", verbose_name="الملف"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف المستند"),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرفع"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الرفع بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستند المشروع",
                "verbose_name_plural": "مستندات المشروع",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المرحلة")),
                ("description", models.TextField(verbose_name="وصف المرحلة")),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء المتوقع")),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء الفعلي"
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="نسبة الإنجاز",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="الميزانية",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرحلة المشروع",
                "verbose_name_plural": "مراحل المشروع",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_role",
                    models.CharField(
                        choices=[
                            ("project_manager", "مدير المشروع"),
                            ("team_member", "عضو فريق"),
                            ("consultant", "مستشار"),
                        ],
                        default="team_member",
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_team_members",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو فريق المشروع",
                "verbose_name_plural": "أعضاء فريق المشروع",
                "unique_together": {("project", "user")},
            },
        ),
    ]
