# Generated by Django 5.1.5 on 2025-01-22 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم العقد"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان العقد")),
                ("description", models.TextField(verbose_name="وصف العقد")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("project", "عقد مشروع"),
                            ("service", "عقد خدمة"),
                            ("supply", "عقد توريد"),
                            ("maintenance", "عقد صيانة"),
                        ],
                        max_length=20,
                        verbose_name="نوع العقد",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "قيد المراجعة"),
                            ("active", "نشط"),
                            ("completed", "مكتمل"),
                            ("terminated", "منتهي"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="حالة العقد",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء")),
                (
                    "signing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التوقيع"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="القيمة الإجمالية"
                    ),
                ),
                (
                    "advance_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="الدفعة المقدمة",
                    ),
                ),
                (
                    "retention_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="نسبة الاستقطاع",
                    ),
                ),
                (
                    "contract_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contracts/",
                        verbose_name="ملف العقد",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="clients.client",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
            ],
            options={
                "verbose_name": "عقد",
                "verbose_name_plural": "العقود",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان البند")),
                ("content", models.TextField(verbose_name="محتوى البند")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="contracts.contract",
                        verbose_name="العقد",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند العقد",
                "verbose_name_plural": "بنود العقد",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContractPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(max_length=50, verbose_name="رقم الدفعة"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("advance", "دفعة مقدمة"),
                            ("progress", "دفعة مرحلية"),
                            ("final", "دفعة نهائية"),
                        ],
                        max_length=20,
                        verbose_name="نوع الدفعة",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="المبلغ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "معتمد"),
                            ("paid", "مدفوع"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "payment_date",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ الدفع"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="contracts.contract",
                        verbose_name="العقد",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة عقد",
                "verbose_name_plural": "دفعات العقود",
                "ordering": ["due_date"],
                "unique_together": {("contract", "payment_number")},
            },
        ),
    ]
