# Generated by Django 5.1.5 on 2025-01-22 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الفئة")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="inventory.category",
                        verbose_name="الفئة الأم",
                    ),
                ),
            ],
            options={
                "verbose_name": "فئة",
                "verbose_name_plural": "الفئات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الرمز"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الصنف")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "قطعة"),
                            ("meter", "متر"),
                            ("kg", "كيلوجرام"),
                            ("liter", "لتر"),
                            ("box", "صندوق"),
                            ("pack", "حزمة"),
                        ],
                        max_length=20,
                        verbose_name="وحدة القياس",
                    ),
                ),
                (
                    "minimum_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الحد الأدنى للكمية",
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="نقطة إعادة الطلب",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الشراء"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر البيع"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.category",
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صنف",
                "verbose_name_plural": "الأصناف",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "مخزون منخفض"),
                            ("expiry", "قرب انتهاء الصلاحية"),
                            ("maintenance_due", "موعد صيانة"),
                            ("warranty_expiry", "انتهاء الضمان"),
                        ],
                        max_length=20,
                        verbose_name="نوع التنبيه",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("resolved", "تمت المعالجة"),
                            ("ignored", "تم التجاهل"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ المعالجة"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تمت المعالجة بواسطة",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="inventory.item",
                        verbose_name="الصنف",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبيه مخزون",
                "verbose_name_plural": "تنبيهات المخزون",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("preventive", "صيانة وقائية"),
                            ("corrective", "صيانة تصحيحية"),
                            ("emergency", "صيانة طارئة"),
                        ],
                        max_length=20,
                        verbose_name="نوع الصيانة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "مجدول"),
                            ("in_progress", "قيد التنفيذ"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("scheduled_date", models.DateTimeField(verbose_name="تاريخ الجدولة")),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ البدء"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف الصيانة")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="التكلفة",
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="تم التنفيذ بواسطة"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_maintenances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenances",
                        to="inventory.item",
                        verbose_name="الصنف",
                    ),
                ),
            ],
            options={
                "verbose_name": "صيانة",
                "verbose_name_plural": "الصيانة",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="الوصف")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="مكتمل"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "maintenance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="inventory.maintenance",
                        verbose_name="الصيانة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة صيانة",
                "verbose_name_plural": "مهام الصيانة",
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الطلب"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "قيد الموافقة"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                            ("ordered", "تم الطلب"),
                            ("received", "تم الاستلام"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("medium", "متوسطة"),
                            ("high", "عالية"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ الإجمالي",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الاعتماد بواسطة",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_requests",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الطلب بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب شراء",
                "verbose_name_plural": "طلبات الشراء",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الكمية"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="السعر الإجمالي"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_request_items",
                        to="inventory.item",
                        verbose_name="الصنف",
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.purchaserequest",
                        verbose_name="طلب الشراء",
                    ),
                ),
            ],
            options={
                "verbose_name": "صنف طلب الشراء",
                "verbose_name_plural": "أصناف طلب الشراء",
            },
        ),
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_date", models.DateField(verbose_name="تاريخ الجرد")),
                (
                    "physical_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الكمية الفعلية"
                    ),
                ),
                (
                    "system_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="كمية النظام"
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الفرق"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الجرد بواسطة",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_counts",
                        to="inventory.item",
                        verbose_name="الصنف",
                    ),
                ),
            ],
            options={
                "verbose_name": "جرد مخزون",
                "verbose_name_plural": "عمليات جرد المخزون",
                "ordering": ["-count_date"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المورد")),
                (
                    "contact_person",
                    models.CharField(max_length=200, verbose_name="الشخص المسؤول"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الجوال"
                    ),
                ),
                ("address", models.TextField(verbose_name="العنوان")),
                (
                    "commercial_record",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="السجل التجاري"
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الرقم الضريبي"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_suppliers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مورد",
                "verbose_name_plural": "الموردين",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("in", "وارد"), ("out", "صادر")],
                        max_length=3,
                        verbose_name="نوع الحركة",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الكمية"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="السعر الإجمالي"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم المرجع"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to="inventory.item",
                        verbose_name="الصنف",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to="inventory.supplier",
                        verbose_name="المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة مخزون",
                "verbose_name_plural": "حركات المخزون",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_requests",
                to="inventory.supplier",
                verbose_name="المورد",
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenances",
                to="inventory.supplier",
                verbose_name="مزود الخدمة",
            ),
        ),
        migrations.CreateModel(
            name="ItemSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر"
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        default=1, verbose_name="مدة التوريد (أيام)"
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(default=False, verbose_name="مورد مفضل"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.item",
                        verbose_name="الصنف",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                        verbose_name="المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "مورد الصنف",
                "verbose_name_plural": "موردي الأصناف",
                "unique_together": {("item", "supplier")},
            },
        ),
        migrations.AddField(
            model_name="item",
            name="suppliers",
            field=models.ManyToManyField(
                related_name="items",
                through="inventory.ItemSupplier",
                to="inventory.supplier",
                verbose_name="الموردين",
            ),
        ),
        migrations.CreateModel(
            name="Warranty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warranty_number",
                    models.CharField(max_length=100, verbose_name="رقم الضمان"),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                ("terms", models.TextField(verbose_name="شروط الضمان")),
                ("coverage", models.TextField(verbose_name="تغطية الضمان")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "ساري"),
                            ("expired", "منتهي"),
                            ("void", "ملغي"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        upload_to="warranty_attachments/",
                        verbose_name="المرفقات",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warranties",
                        to="inventory.item",
                        verbose_name="الصنف",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warranties",
                        to="inventory.supplier",
                        verbose_name="مزود الضمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "ضمان",
                "verbose_name_plural": "الضمانات",
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluation_date", models.DateField(verbose_name="تاريخ التقييم")),
                (
                    "quality_rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="تقييم الجودة",
                    ),
                ),
                (
                    "delivery_rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="تقييم التسليم",
                    ),
                ),
                (
                    "price_rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="تقييم السعر",
                    ),
                ),
                (
                    "service_rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="تقييم الخدمة",
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="تقييم التواصل",
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="التقييم الإجمالي"
                    ),
                ),
                ("strengths", models.TextField(blank=True, verbose_name="نقاط القوة")),
                ("weaknesses", models.TextField(blank=True, verbose_name="نقاط الضعف")),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="التوصيات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_evaluations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التقييم بواسطة",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="inventory.supplier",
                        verbose_name="المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم مورد",
                "verbose_name_plural": "تقييمات الموردين",
                "ordering": ["-evaluation_date"],
                "unique_together": {("supplier", "evaluation_date")},
            },
        ),
    ]
