# Generated by Django 5.1.5 on 2025-01-22 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("hr", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان التقرير"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("project_progress", "تقرير تقدم المشروع"),
                            ("financial", "تقرير مالي"),
                            ("hr", "تقرير موارد بشرية"),
                            ("inventory", "تقرير مخزون"),
                            ("client", "تقرير عملاء"),
                            ("contract", "تقرير عقود"),
                            ("custom", "تقرير مخصص"),
                        ],
                        max_length=20,
                        verbose_name="نوع التقرير",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف التقرير")),
                ("content", models.TextField(verbose_name="محتوى التقرير")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الاعتماد بواسطة",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="contracts.contract",
                        verbose_name="العقد",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="hr.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير",
                "verbose_name_plural": "التقارير",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المرفق"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="report_attachments/", verbose_name="الملف"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف المرفق"),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرفع"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="reports.report",
                        verbose_name="التقرير",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الرفع بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرفق التقرير",
                "verbose_name_plural": "مرفقات التقرير",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم القالب")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("project_progress", "تقرير تقدم المشروع"),
                            ("financial", "تقرير مالي"),
                            ("hr", "تقرير موارد بشرية"),
                            ("inventory", "تقرير مخزون"),
                            ("client", "تقرير عملاء"),
                            ("contract", "تقرير عقود"),
                            ("custom", "تقرير مخصص"),
                        ],
                        max_length=20,
                        verbose_name="نوع التقرير",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف القالب")),
                ("template_content", models.TextField(verbose_name="محتوى القالب")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب تقرير",
                "verbose_name_plural": "قوالب التقارير",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "يومي"),
                            ("weekly", "أسبوعي"),
                            ("monthly", "شهري"),
                            ("quarterly", "ربع سنوي"),
                        ],
                        max_length=20,
                        verbose_name="التكرار",
                    ),
                ),
                ("next_run", models.DateTimeField(verbose_name="التشغيل القادم")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to="hr.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="report_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستلمون",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reports.reporttemplate",
                        verbose_name="قالب التقرير",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدولة تقرير",
                "verbose_name_plural": "جدولة التقارير",
                "ordering": ["next_run"],
            },
        ),
    ]
